Add Posts and users
gango-anan/members-only pull request #1
Opened 2021-02-06 00:54 UTC by gango-anan

# In the members-only app project, I:
- Created a Post model and a posts controller.
- Created a resource in the routes file which allows [:new, :create, :index] methods.
- Added #before_actions to restrict access to the #new and #create methods to only signed-in users.
- Added code to the #new method to facilitate the creation of a new post.
- Created a simple form for creating a new post.
- Added code to the #create action, to aid in creating a new post associated with the currently signed-in user
with the ability to redirect to the index view if the post creation was successful.
- Added logic to the posts index view to display the post author's name only if a user is logged in.

2021-02-06 01:18 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've really done well so far in this project. Your readme is awesome :clap:
However, some changes are required before it can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] You have to create the application routes using `resources :posts, only: [:new, :create, :index]`
- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. .browserslistrc)
- [ ] Check my in-line comments below for other required changes.

**[ OPTIONAL CHANGES ]**

- [ ] Kindly add label to your text fields, most especially the sign-up and login forms.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-02-06 01:18 UTC, teekaytech commented on app/controllers/posts_controller.rb
> +  # before_action :set_post, only: [:destroy]
Kindly remove the commented code.

2021-02-06 01:18 UTC, teekaytech commented on app/controllers/posts_controller.rb
> +  # end
It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history

2021-02-06 01:18 UTC, teekaytech commented on app/views/posts/index.html.erb
> +      <% end %>
Kindly move all view-related logic to the view helper.
There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.
      **Resources**
- [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
- [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2021-02-06 21:49 UTC, gango-anan commented
@teekaytech, the review was powerful I learned a ton of stuff from it, and I  have Implemented all the required changes including the optional ones, thanks.

2021-02-06 22:59 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General


- [x]

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2021-02-06 23:18 UTC, gango-anan commented
Hello @kobiyoyo, kindly double-check the issue of the route from your side because in my local environment all is working well and even the live version on Heroku is running well and it's the same version as my local one.

2021-02-07 00:21 UTC, kevincappuccino approved these changes
# [STATUS] PROJECT APPROVED 🍾

### I really like your project! Congrats @gango-anan, you did an excellent job, you have my approval to go ahead and merge this pull request!

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2021-02-08 15:32 UTC, merged